### ISSUE TITLE
Update the Password Managers

### ISSUE THREAD

**Issue by oldphones68** [learn-anything/firefox-extensions#9]
According to some authentic sources like [PrivacyTools.io](https://privacytools.io/software/passwords/) and [prism-break](https://prism-break.org/en/subcategories/windows-password-managers/), Lastpass, 1password etc. are _NOT_ secure.
May we replace that (1password) with some better alternative like Bitwarden or KeePassXC?

**Comment by oldphones68** [comment]
Probably can be fixed through merging #10.

**Comment by nikivdev** [comment]
This is not too privacy conscious and 1pass has great UX so I suggest we keep it. Can add more password managers that are good and ideally secure too. 

There are levels of privacy and 1pass works good for a general citizen I'd say.

**Comment by oldphones68** [comment]
Okey! :)
